In [1]:
import pandas as pd
import string
import re
import datetime

In [3]:
def parse(text):
    no_punctuation = text.translate(str.maketrans('', '', string.punctuation))
    no_small_words = re.sub(r'\b\w{1,3}\b', '', no_punctuation.lower())
    no_big_spaces = re.sub(' +', ' ', no_small_words)
    return no_big_spaces

In [7]:
df = pd.read_csv('/home/pietro/Documenti/BigData/first_project_baronato//Reviews_parsed.csv')

In [8]:
df

,Id,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,1,1,5,2011,have bought several vitality canned food prod...
1,2,B00813GRG4,A1D87F6ZCVE5NK,0,0,1,2012,product arrived labeled jumbo salted peanutsth...
2,3,B000LQOCH0,ABXLMWJIXXAIN,1,1,4,2008,this confection that been around centuries lig...
3,4,B000UA0QIQ,A395BORC6FGVXV,3,3,2,2011,looking secret ingredient robitussin believe ...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,0,0,5,2012,great taffy great price there wide assortment ...
...,...,...,...,...,...,...,...,...
568449,568450,B001EO7N10,A28KG5XORO54AY,0,0,5,2011,great sesame chickenthis good better than rest...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,0,0,2,2012,disappointed with flavor chocolate notes espe...
568451,568452,B004I613EE,A121AA1GQV751Z,2,2,5,2012,these stars small give 1015 those training ses...
568452,568453,B004I613EE,A3IBEVCTXKNOH,1,1,5,2012,these best treats training rewarding your bein...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,0,0,5,2012,very satisfied product advertised cereal with...

In [12]:
count = 0
for i in range(0, len(df)):
    if '   ' in df.at[i, 'Text']:
        count += 1
        # print(df.at[i, 'Text'])
print(count)

0

In [3]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [7]:
df = df.drop(['ProfileName', 'Summary'], axis = 1)

In [8]:
df

,Id,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,1,1,5,1303862400,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,0,0,1,1346976000,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,1,1,4,1219017600,This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,3,3,2,1307923200,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,0,0,5,1350777600,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...
568449,568450,B001EO7N10,A28KG5XORO54AY,0,0,5,1299628800,Great for sesame chicken..this is a good if no...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,0,0,2,1331251200,I'm disappointed with the flavor. The chocolat...
568451,568452,B004I613EE,A121AA1GQV751Z,2,2,5,1329782400,"These stars are small, so you can give 10-15 o..."
568452,568453,B004I613EE,A3IBEVCTXKNOH,1,1,5,1331596800,These are the BEST treats for training and rew...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,0,0,5,1338422400,"I am very satisfied ,product is as advertised,..."

In [10]:
for i in range(0, len(df)):
    df.at[i, 'Text'] = parse(df.at[i, 'Text'])
    try:
        date_time = datetime.datetime.fromtimestamp(int(df.at[i, 'Time']))
    except ValueError:
        continue
    date = date_time.strftime('%Y-%m-%d %H:%M:%S')
    year = date.split('-')[0]
    try:
        int_year = int(year)
    except ValueError:
        continue
    df.at[i, 'Time'] = int_year

In [11]:
df

,Id,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,1,1,5,2011,have bought several vitality canned food p...
1,2,B00813GRG4,A1D87F6ZCVE5NK,0,0,1,2012,product arrived labeled jumbo salted peanutst...
2,3,B000LQOCH0,ABXLMWJIXXAIN,1,1,4,2008,this confection that been around centurie...
3,4,B000UA0QIQ,A395BORC6FGVXV,3,3,2,2011,looking secret ingredient robitussin be...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,0,0,5,2012,great taffy great price there wide assort...
...,...,...,...,...,...,...,...,...
568449,568450,B001EO7N10,A28KG5XORO54AY,0,0,5,2011,great sesame chickenthis good better than...
568450,568451,B003S1WTCU,A3I8AFVPEE8KI5,0,0,2,2012,disappointed with flavor chocolate notes e...
568451,568452,B004I613EE,A121AA1GQV751Z,2,2,5,2012,these stars small give 1015 those train...
568452,568453,B004I613EE,A3IBEVCTXKNOH,1,1,5,2012,these best treats training rewarding your ...
568453,568454,B001LR2CU2,A3LGQPJCZVL9UC,0,0,5,2012,very satisfied product advertised cere...

In [12]:
print(df['Time'].unique())

[2011 2012 2008 2005 2010 2009 2006 2007 2004 2000 2003 2002 2001 1999]

In [13]:
df.to_csv(r'.\..\..\Reviews_parsed.csv', index = None)